services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - cluster.routing.allocation.disk.watermark.low=99%
      - cluster.routing.allocation.disk.watermark.high=99%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.routing.allocation.disk.watermark.flood_stage.frozen=99%
      - cluster.info.update.interval=1m
    network_mode: "host"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
      - XPACK_SECURITY_ENABLED=false
    network_mode: "host"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    network_mode: "host"
    environment:
      - xpack.monitoring.enabled=false
    user: "0:0"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./auth.log:/var/log/auth.log:ro

volumes:
  esdata:
